### ISSUE TITLE
Incorrect table_catalog, result in trying to create "migrations" table again

### ISSUE THREAD

**Issue by danielcdcj** [db-migrate/cockroachdb#10]
I'm using cockroachlabs.cloud to host my db.
I created and ran migration the first time perfectly; tables were created correctly.

However, if I run migration again, it says that the "migrations" table already exists.
![Screen Shot 2023-02-26 at 00 06 51](https://user-images.githubusercontent.com/5447994/221399740-f13d6d28-565e-4db8-8e50-22d7db77ce49.png)

It turns out it couldn't find the "migrations" table in "information_schema.tables" since the field I have for "table_catalog" only consists of db name and doesn't consist of the cluster_identifier (shown as 'dark-sardine-xx1' in the screenshots)
![Screen Shot 2023-02-26 at 00 09 21](https://user-images.githubusercontent.com/5447994/221399922-67ea0886-6fdf-4d29-bc78-a8e2003ad678.png)

I could see the record by removing the table_catalog filter
![Screen Shot 2023-02-26 at 00 19 48](https://user-images.githubusercontent.com/5447994/221399928-a14ab461-ed10-42b6-8beb-537c25badbb0.png)

I'm looking for a way to disable filtering by table_catalog.
This is the line in this repo for this, but wonder what I could do.
![Screen Shot 2023-02-26 at 00 12 03](https://user-images.githubusercontent.com/5447994/221400063-43691f6b-eae8-41a2-9e1b-80e7720c28e2.png)

**Comment by wzrdtales** [comment]
please never post screenshots of text...

anyhow, just enter the correct database name, why do you add that prefix there in the first place?

**Comment by danielcdcj** [comment]
I have to put in the cluster identifier; if not, I would get this following error:
```[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: codeParamsRoutingFailed: missing cluster identifier```

**Comment by wzrdtales** [comment]
This is a bug of cockroach then please open a ticket in their repo.

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick
________________________________
Von: Daniel Hsieh ***@***.***>
Gesendet: Sonntag, 26. Februar 2023 23:55
An: db-migrate/cockroachdb
Cc: Tobias Gurtzick; Comment
Betreff: Re: [db-migrate/cockroachdb] Incorrect table_catalog, result in trying to create "migrations" table again (Issue #10) 

I have to put in the cluster identifier; if not, I would get this following error:
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: codeParamsRoutingFailed: missing cluster identifier

**Comment by wzrdtales** [comment]
Normal non cockroach cloud DBS are not behaving like that

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick
________________________________
Von: Daniel Hsieh ***@***.***>
Gesendet: Sonntag, 26. Februar 2023 23:55
An: db-migrate/cockroachdb
Cc: Tobias Gurtzick; Comment
Betreff: Re: [db-migrate/cockroachdb] Incorrect table_catalog, result in trying to create "migrations" table again (Issue #10) 

I have to put in the cluster identifier; if not, I would get this following error:
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: codeParamsRoutingFailed: missing cluster identifier

**Comment by wzrdtales** [comment]
Since you closed it I guess you opened the ticket with cockroachdb? Any response over there?

**Comment by danielcdcj** [comment]
Hi I did not open a ticket there. I switched to using PlanetScale, which is basically MySQL and works perfectly so far.

**Comment by wzrdtales** [comment]
Alright never heard about that one yet. Good luck with that

Sent from Nine

-- 

Best

--
Tobias Gurtzick
CEO
WizardTales GmbH

Additional Contacts:
@github | ***@***.***
--
Website: https://www.wizardtales.com
***@***.***
nmlpm: -- coming soon & open source --

Please tag your mails with "request", "issue" or "proposal", unless none of these fit or there already exists a thread.

-- Why should one reach for what one may be capable reaching, that's awfully boring and after all one still be ones yesterday being. --

Sitz der Gesellschaft: Ratingen
Kokkolastr. 5
40882 Ratingen
Germany

Registergericht: Amtsgericht Düsseldorf, HRB 84140
Geschäftsführer: Tobias Gurtzick

________________________________
Von: Daniel Hsieh ***@***.***>
Gesendet: Dienstag, 7. März 2023 00:02
An: db-migrate/cockroachdb
Cc: Tobias Gurtzick; Comment
Betreff: Re: [db-migrate/cockroachdb] Incorrect table_catalog, result in trying to create "migrations" table again (Issue #10) 

Hi I did not open a ticket there. I switched to using PlanetScale, which is basically MySQL and works perfectly so far.
